[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.52.4",
    "torch>=2.0.0",
    "torchvision>=0.29.0",
    "tqdm>=4.70.1",
    "matplotlib>=3.11.2",
    "python-multipart>=0.0.32",
]
